language: node_js
version: 1.0
node_js:
  - '8'
dist: trusty
sudo: false

cache:
  directories:
    - node_modules

script:
  - yarn test
  - yarn build_lib
  - yarn build:prod

before_deploy:
  - cd dist/@snappcar/date-time-range-picker
deploy:
  - provider: npm
    edge: true
    cleanup: false
    email: 'devops@snappcar.nl'
    api_key: $NPM_TOKEN
    on:
      branch: master
  - provider: pages
    edge: true
    cleanup: false
    github-token: $GITHUB_TOKEN # Set in travis-ci.org dashboard
    local-dir: dist/date-time-range-picker-app
    on:
      branch: master
after_deploy:
  - cd ../../../
