language: node_js
node_js:
  - "8"
dist: trusty
sudo: false

cache:
  directories:
    - node_modules

script:
  - yarn test
  - yarn build_lib
  - yarn build:prod

deploy:
  - provider: npm
    skip-cleanup: true
    email: "devops@snappcar.nl"
    local-dir: dist/@snappcar/date-time-range-picker
    api_key: $NPM_TOKEN
    on:
      all_branches: true
  - provider: pages
    skip-cleanup: true
    github-token: $GITHUB_TOKEN # Set in travis-ci.org dashboard
    local-dir: dist/date-time-range-picker-app
    on:
      all_branches: false