language: node_js
node_js:
  - "8"
dist: trusty
sudo: false

cache:
  directories:
    - node_modules

branches:
  only:
  - master

script:
  - yarn test
  - yarn build_lib
  - yarn build --prod

deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_TOKEN # Set in travis-ci.org dashboard
  local-dir: dist/date-time-range-picker-app
  on:
    branch: master